Repository kids-first/kf-api-dataservice, pull requests merged in 2018-06, with the labels that each got.

#361 🐛 Fix repeated loading of jinja tempaltes
  bin/supervisord.conf
  dataservice/api/common/views.py
  requirements.txt
Labels: bug

#365 ✨ Patch acl
  dataservice/api/common/model.py
  dataservice/api/common/pagination.py
  dataservice/api/genomic_file/resources.py
  dataservice/api/study_file/resources.py
  dataservice/extensions/flask_indexd.py
  tests/genomic_file/test_genomic_file_models.py
  tests/genomic_file/test_genomic_file_resources.py
  tests/mocks.py
  tests/study_file/test_study_file_models.py
  tests/study_file/test_study_file_resources.py
Labels: Ready for review, feature

#374 🚑 Use explicit updates when update indexd fields
  .circleci/config.yml
  config.py
  dataservice/api/common/model.py
  dataservice/api/genomic_file/resources.py
  dataservice/api/study_file/resources.py
  tests/genomic_file/test_genomic_file_models.py
  tests/study_file/test_study_file_models.py
Labels: Ready for review, bug

#379 🔊 Add logging for requests
  dataservice/__init__.py
Labels: devops

#377 🐛 Allow independent updates for size and hashes
  dataservice/extensions/flask_indexd.py
  tests/genomic_file/test_genomic_file_models.py
  tests/mocks.py
Labels: bug

#380 🐛 Update API docs - correct version of code
  dataservice/api/common/schemas.py
  dataservice/api/common/views.py
  dataservice/api/templates/delete_by_id.yml
  dataservice/api/templates/get_by_id.yml
  dataservice/api/templates/new_resource.yml
  dataservice/api/templates/update_by_id.yml
Labels: bug, documentation

#373 🐛 Fix 500 error on /studies?study_id
  dataservice/api/study/resources.py
  tests/test_filter_params.py
Labels: Ready for review, bug

#352 ✨ Read groups
  dataservice/__init__.py
  dataservice/api/common/custom_fields.py
  dataservice/api/common/validation.py
  dataservice/api/genomic_file/models.py
  dataservice/api/genomic_file/schemas.py
  dataservice/api/read_group/__init__.py
  dataservice/api/read_group/models.py
  dataservice/api/read_group/resources.py
  dataservice/api/read_group/schemas.py
  docs/erd.png
  migrations/versions/dbe23598a508_.py
  tests/conftest.py
  tests/data.json
  tests/genomic_file/test_genomic_file_resources.py
  tests/read_group/test_read_group_model.py
  tests/read_group/test_read_group_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: Ready for review, data model

#359 ✨ Add relation from biospecimen to diagnosis
  dataservice/__init__.py
  dataservice/api/biospecimen/models.py
  dataservice/api/biospecimen/schemas.py
  dataservice/api/diagnosis/models.py
  dataservice/api/diagnosis/schemas.py
  dataservice/api/errors.py
  docs/erd.png
  migrations/versions/5b903b00dce4_.py
  tests/diagnosis/test_diagnosis_models.py
  tests/diagnosis/test_diagnosis_resources.py
  tests/test_api.py
Labels: Ready for review, data model

#386 🐛 Fix sns mocks
  tests/conftest.py
  tests/test_events.py
Labels: bug
