Repository kids-first/kf-api-dataservice, pull requests merged in 2018-09, with the labels that each got.

#437 🐛 Fix join for genomic files study filter
  dataservice/api/genomic_file/resources.py
Labels: bug

#439 🐛 Remove duplicates from join results
  dataservice/api/cavatica_task/resources.py
  dataservice/api/cavatica_task_genomic_file/resources.py
  dataservice/api/sequencing_experiment/resources.py
Labels: bug

#443 ♻️ Don't use rev in indexd requests
  dataservice/extensions/flask_indexd.py
  tests/genomic_file/test_genomic_file_resources.py
Labels: bug, refactor

#447 ✨Move consent_type from participant to biospecimen
  dataservice/api/biospecimen/models.py
  dataservice/api/participant/models.py
  docs/erd.png
  migrations/versions/7f0b46d388a1_.py
  tests/biospecimen/test_biospecimen_models.py
  tests/biospecimen/test_biospecimen_resources.py
  tests/data.json
  tests/family/test_family_models.py
  tests/participant/test_participant_models.py
  tests/participant/test_participant_resources.py
  tests/test_pagination.py
Labels: data model, refactor
