Repository kids-first/kf-api-dataservice, pull requests merged in 2018-04, with the labels that each got.

#215 🐛 Put back dockerfile command
  Dockerfile
Labels: bug

#216 🐛 Use run script to upgrade db before supervisor
  Dockerfile
Labels: bug

#197 ✨Study file resource
  dataservice/api/__init__.py
  dataservice/api/study_file/__init__.py
  dataservice/api/study_file/resources.py
  dataservice/api/study_file/schemas.py
  tests/conftest.py
  tests/investigator/test_investigator_resources.py
  tests/study/test_study_resources.py
  tests/study_file/test_study_file_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: feature

#214 🕷fixing
  Jenkinsfile
Labels: bug

#218 ✨ Merging participant and demographic
  dataservice/__init__.py
  dataservice/api/__init__.py
  dataservice/api/demographic/README.md
  dataservice/api/demographic/__init__.py
  dataservice/api/demographic/models.py
  dataservice/api/demographic/resources.py
  dataservice/api/demographic/schemas.py
  dataservice/api/participant/models.py
  dataservice/api/participant/resources.py
  dataservice/util/data_gen/data_generator.py
  docs/erd.png
  migrations/versions/b2aab064a0b6_.py
  tests/conftest.py
  tests/demographic/test_demographic_models.py
  tests/demographic/test_demographic_resources.py
  tests/participant/test_participant_models.py
  tests/participant/test_participant_resources.py
  tests/test_api.py
  tests/test_errors.py
  tests/test_pagination.py
  tests/test_swagger.py
Labels: Ready for review

#219 👪 Family model and resources
  dataservice/__init__.py
  dataservice/api/__init__.py
  dataservice/api/family/README.md
  dataservice/api/family/__init__.py
  dataservice/api/family/models.py
  dataservice/api/family/resources.py
  dataservice/api/family/schemas.py
  dataservice/api/family_relationship/schemas.py
  dataservice/api/participant/models.py
  dataservice/api/participant/schemas.py
  docs/erd.png
  migrations/versions/a10ebb4c43c7_.py
  tests/conftest.py
  tests/family/test_family_models.py
  tests/family/test_family_resources.py
  tests/participant/test_participant_models.py
  tests/participant/test_participant_resources.py
  tests/test_api.py
Labels: Ready for review, feature

#204 ✨Model updates
  dataservice/api/diagnosis/models.py
  dataservice/api/genomic_file/models.py
  dataservice/api/phenotype/models.py
  dataservice/api/study/models.py
  dataservice/util/data_gen/data_generator.py
  docs/erd.png
  migrations/env.py
  migrations/versions/6c5b80679ee3_.py
  tests/aliquot/test_aliquot_models.py
  tests/conftest.py
  tests/diagnosis/test_diagnosis_models.py
  tests/diagnosis/test_diagnosis_resources.py
  tests/genomic_file/test_genomic_file_models.py
  tests/phenotype/test_phenotype_models.py
  tests/phenotype/test_phenotype_resources.py
  tests/sample/test_sample_models.py
  tests/sample/test_sample_resources.py
  tests/study/test_study_models.py
  tests/study/test_study_resources.py
Labels: Ready for review, data model

#196 ✨ Alias Group Model (for participant aliases)
  dataservice/api/participant/models.py
  dataservice/util/data_gen/data_generator.py
  docs/erd.png
  tests/participant/test_alias_models.py
Labels: Ready for review, data model

#235 🐛 fix backref's for diagnoses, outcomes, phenotypes in participant model
  dataservice/api/participant/models.py
Labels: Ready for review, bug, data model

#238 🗃 Add missing alias_group migration
  migrations/versions/04c620f9f768_.py
Labels: bug, data model

#228 ✨Biospecimen model
  dataservice/__init__.py
  dataservice/api/__init__.py
  dataservice/api/aliquot/__init__.py
  dataservice/api/aliquot/models.py
  dataservice/api/aliquot/resources.py
  dataservice/api/aliquot/schemas.py
  dataservice/api/biospecimen/__init__.py
  dataservice/api/biospecimen/models.py
  dataservice/api/biospecimen/resources.py
  dataservice/api/biospecimen/schemas.py
  dataservice/api/genomic_file/models.py
  dataservice/api/participant/models.py
  dataservice/api/participant/resources.py
  dataservice/api/sample/__init__.py
  dataservice/api/sample/models.py
  dataservice/api/sample/resources.py
  dataservice/api/sample/schemas.py
  dataservice/api/sequencing_experiment/models.py
  dataservice/api/sequencing_experiment/schemas.py
  dataservice/util/data_gen/data_generator.py
  docs/erd.png
  migrations/versions/e3ee14b87b2e_.py
  tests/aliquot/test_aliquot_models.py
  tests/aliquot/test_aliquot_resources.py
  tests/biospecimen/test_biospecimen_models.py
  tests/biospecimen/test_biospecimen_resources.py
  tests/conftest.py
  tests/genomic_file/test_genomic_file_models.py
  tests/sample/test_sample_models.py
  tests/sequencing_experiment/test_sequencing_experiment_resources.py
  tests/sequencing_experiment/test_sequencingexperiment_models.py
  tests/test_api.py
  tests/test_errors.py
  tests/test_pagination.py
  tests/test_swagger.py
  tests/workflow/test_workflow_models.py
Labels: Ready for review, data model

#145 ✨ Genomic file resource
  README.md
  config.py
  dataservice/__init__.py
  dataservice/api/__init__.py
  dataservice/api/common/model.py
  dataservice/api/common/schemas.py
  dataservice/api/errors.py
  dataservice/api/genomic_file/__init__.py
  dataservice/api/genomic_file/models.py
  dataservice/api/genomic_file/resources.py
  dataservice/api/genomic_file/schemas.py
  dataservice/extensions/__init__.py
  dataservice/extensions/flask_indexd.py
  dataservice/util/data_gen/data_generator.py
  dev-requirements.txt
  migrations/versions/243980a97e4c_.py
  tests/conftest.py
  tests/genomic_file/test_genomic_file_models.py
  tests/genomic_file/test_genomic_file_resources.py
  tests/integrations/indexd.py
  tests/mocks.py
  tests/test_api.py
  tests/test_pagination.py
  tests/utils.py
  tests/workflow/test_workflow_models.py
Labels: Ready for review, feature

#230 Filter Resources by Study
  dataservice/api/README.md
  dataservice/api/biospecimen/resources.py
  dataservice/api/common/pagination.py
  dataservice/api/common/schemas.py
  dataservice/api/diagnosis/resources.py
  dataservice/api/family/resources.py
  dataservice/api/family_relationship/resources.py
  dataservice/api/genomic_file/resources.py
  dataservice/api/investigator/resources.py
  dataservice/api/outcome/resources.py
  dataservice/api/participant/resources.py
  dataservice/api/phenotype/resources.py
  dataservice/api/sequencing_experiment/resources.py
  dataservice/api/study_file/resources.py
  tests/test_pagination.py
Labels: Ready for review, feature

#250 ⚡️Optimize loading of children in default pagination
  dataservice/api/biospecimen/resources.py
  dataservice/api/family/resources.py
  dataservice/api/investigator/resources.py
  dataservice/api/sequencing_experiment/resources.py
  dataservice/api/study/resources.py
Labels: Ready for review, feature

#256 📝 Update entity relationship diagram
  docs/erd.png
Labels: data model

#252 💄 Center logo and badges
  README.md
Labels: Ready for review, documentation

#258 🐛Delete parent orphans
  dataservice/api/family/models.py
  dataservice/api/participant/models.py
  dataservice/api/sequencing_experiment/models.py
  tests/family/test_family_models.py
  tests/participant/test_alias_models.py
  tests/sequencing_experiment/test_sequencingexperiment_models.py
Labels: Ready for review, data model

#261 ✨ Relation links
  dataservice/api/biospecimen/schemas.py
  dataservice/api/common/custom_fields.py
  dataservice/api/genomic_file/schemas.py
  dataservice/api/participant/schemas.py
  dataservice/api/sequencing_experiment/schemas.py
  dataservice/api/study/schemas.py
  tests/participant/test_participant_resources.py
  tests/study/test_study_resources.py
  tests/test_api.py
Labels: Ready for review, bug

#262 ✨Model Changes
  dataservice/api/biospecimen/models.py
  dataservice/api/diagnosis/models.py
  dataservice/api/family_relationship/models.py
  dataservice/api/genomic_file/models.py
  dataservice/api/investigator/models.py
  dataservice/api/outcome/models.py
  dataservice/api/phenotype/models.py
  dataservice/api/sequencing_center/models.py
  dataservice/api/study/models.py
  dataservice/api/study_file/models.py
  dataservice/api/workflow/models.py
  docs/erd.png
  migrations/versions/d9ba1b15d196_.py
  tests/biospecimen/test_biospecimen_models.py
  tests/biospecimen/test_biospecimen_resources.py
  tests/conftest.py
  tests/diagnosis/test_diagnosis_models.py
  tests/diagnosis/test_diagnosis_resources.py
  tests/genomic_file/test_genomic_file_models.py
  tests/genomic_file/test_genomic_file_resources.py
  tests/investigator/test_investigator_models.py
  tests/investigator/test_investigator_resources.py
  tests/outcome/test_outcome_models.py
  tests/outcome/test_outcome_resources.py
  tests/phenotype/test_phenotype_models.py
  tests/phenotype/test_phenotype_resources.py
  tests/sequencing_center/test_seq_center_models.py
  tests/sequencing_center/test_seq_center_resources.py
  tests/study/test_study_models.py
  tests/study_file/test_study_file_models.py
  tests/study_file/test_study_file_resources.py
  tests/test_api.py
  tests/test_pagination.py
  tests/workflow/test_workflow_models.py
Labels: Ready for review, data model
