Repository kids-first/kf-api-dataservice, pull requests merged in 2018-07, with the labels that each got.

#389 ✨ Add More than One Race to race enum
  dataservice/api/participant/schemas.py
Labels: data-import, ready-for-review

#392 🐛 Use correct capitalization for more than one race
  dataservice/api/participant/schemas.py
Labels: ready-for-review

#382 ♻️ Refactor Family Relationships
  dataservice/api/common/schemas.py
  dataservice/api/family_relationship/models.py
  dataservice/api/family_relationship/resources.py
  dataservice/api/family_relationship/schemas.py
  docs/erd.png
  migrations/versions/ce359a457d3d_.py
  tests/conftest.py
  tests/data.json
  tests/family_relationship/test_family_relationship_models.py
  tests/family_relationship/test_family_relationship_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: feature, ready-for-review, refactor
