Repository kids-first/kf-api-dataservice, pull requests merged in 2018-03, with the labels that each got.

#157 Readme image
  README.md
  docs/dataservice.png
Labels: documentation

#170 👷 Add codacy integration
  .circleci/config.yml
  README.md
  dataservice/commands.py
  dev-requirements.txt
Labels: devops, feature

#158 🐛 Fix self links
  dataservice/api/common/pagination.py
  dataservice/api/common/schemas.py
  tests/test_pagination.py
Labels: bug

#174 ✨ Add pagination to resources
  dataservice/api/demographic/resources.py
  dataservice/api/demographic/schemas.py
  dataservice/api/diagnosis/resources.py
  dataservice/api/diagnosis/schemas.py
  dataservice/api/sample/resources.py
  dataservice/api/sample/schemas.py
  tests/test_pagination.py
Labels: feature

#179 🔥 Remove SQLite configuration
  dataservice/__init__.py
Labels: refactor

#178 ♻️ Rename participant tests to conform to naming convention
  tests/participant/test_participant_models.py
  tests/participant/test_participant_resources.py
Labels: refactor

#181 👷 Added jenkins webhook property
  Jenkinsfile
Labels: devops

#177 🔒 Avoid system calls during status request
  dataservice/__init__.py
  dataservice/api/common/schemas.py
  dataservice/api/status/resources.py
  tests/test_api.py
Labels: refactor

#183 ♻️ Fix self links
  dataservice/api/common/schemas.py
  dataservice/api/demographic/schemas.py
  dataservice/api/diagnosis/schemas.py
  dataservice/api/participant/schemas.py
  dataservice/api/sample/schemas.py
  tests/test_pagination.py
Labels: bug, refactor

#173 ✨ ⚡️Change PUT to PATCH in all resource APIs and minor updates
  dataservice/__init__.py
  dataservice/api/common/schemas.py
  dataservice/api/common/views.py
  dataservice/api/demographic/resources.py
  dataservice/api/demographic/schemas.py
  dataservice/api/diagnosis/resources.py
  dataservice/api/diagnosis/schemas.py
  dataservice/api/docs/resources.py
  dataservice/api/participant/resources.py
  dataservice/api/sample/resources.py
  dataservice/api/sample/schemas.py
  dataservice/api/templates/update_by_id.yml
  dataservice/extensions.py
  tests/conftest.py
  tests/demographic/test_demographic_resources.py
  tests/diagnosis/test_diagnosis_resources.py
  tests/participant/test_participant_resources.py
  tests/sample/test_sample_resources.py
  tests/test_api.py
Labels: feature, refactor

#175 ✨ Study resource
  dataservice/api/__init__.py
  dataservice/api/study/__init__.py
  dataservice/api/study/resources.py
  dataservice/api/study/schemas.py
  tests/conftest.py
  tests/study/test_study_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: feature

#176 ✨ Investigator resource
  dataservice/api/__init__.py
  dataservice/api/investigator/__init__.py
  dataservice/api/investigator/resources.py
  dataservice/api/investigator/schemas.py
  tests/conftest.py
  tests/investigator/test_investigator_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: feature

#84 ✨ Aliquot resource
  dataservice/api/__init__.py
  dataservice/api/aliquot/__init__.py
  dataservice/api/aliquot/resources.py
  dataservice/api/aliquot/schemas.py
  dataservice/api/common/custom_fields.py
  dataservice/api/common/validation.py
  tests/aliquot/test_aliquot_resources.py
  tests/conftest.py
  tests/test_api.py
  tests/test_pagination.py
Labels: feature

#189 ✨Add outcome endpoint
  dataservice/api/__init__.py
  dataservice/api/outcome/__init__.py
  dataservice/api/outcome/resources.py
  dataservice/api/outcome/schemas.py
  tests/conftest.py
  tests/outcome/test_outcome_resources.py
  tests/test_api.py
  tests/test_errors.py
  tests/test_pagination.py
Labels: feature

#180 ✨ Add phenotype endpoint
  dataservice/api/__init__.py
  dataservice/api/phenotype/__init__.py
  dataservice/api/phenotype/resources.py
  dataservice/api/phenotype/schemas.py
  tests/conftest.py
  tests/phenotype/test_phenotype_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: feature

#190 ✨ Sequencing Experiment Resource
  dataservice/api/__init__.py
  dataservice/api/sequencing_experiment/__init__.py
  dataservice/api/sequencing_experiment/resources.py
  dataservice/api/sequencing_experiment/schemas.py
  tests/conftest.py
  tests/sequencing_experiment/test_sequencing_experiment_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: feature

#200 🐳 Use nginx for main proxy
  Dockerfile
  bin/nginx.conf
  bin/run.sh
  bin/supervisord.conf
  docker-compose.yml
Labels: devops
