Repository kids-first/kf-api-dataservice, pull requests merged in 2018-05, with the labels that each got.

#283 🐛 Change modified_at field on update
  dataservice/api/common/model.py
  tests/participant/test_participant_models.py
  tests/participant/test_participant_resources.py
Labels: bug

#284 ⚡️ Faster tests
  tests/test_api.py
  tests/test_pagination.py
Labels: Ready for review, refactor

#289 ✨ Update sequencing_experiment_id to be nullable in genomic_file
  dataservice/api/genomic_file/models.py
  dataservice/api/genomic_file/schemas.py
  migrations/versions/7d7df8d524f7_.py
  tests/genomic_file/test_genomic_file_models.py
  tests/genomic_file/test_genomic_file_resources.py
  tests/test_api.py
  tests/test_errors.py
  tests/test_ids.py
  tests/test_pagination.py
  tests/test_swagger.py
Labels: data model

#302 🗃 Remove null constraint on biospecimen_id in genomic file
  dataservice/api/genomic_file/models.py
  dataservice/api/genomic_file/schemas.py
  migrations/versions/669514359df5_.py
  tests/genomic_file/test_genomic_file_models.py
  tests/genomic_file/test_genomic_file_resources.py
Labels: data model

#300 🐛 Fix bug w shipment_date = null
  dataservice/api/biospecimen/schemas.py
  dataservice/api/common/custom_fields.py
  tests/biospecimen/test_biospecimen_resources.py
Labels: bug

#304 🐛 Fix bug w experiment_date = null
  dataservice/api/sequencing_experiment/schemas.py
  tests/sequencing_experiment/test_sequencing_experiment_resources.py
Labels: Ready for review, bug

#305 ✨ Move acl to root document
  dataservice/api/common/model.py
  dataservice/api/common/schemas.py
  dataservice/extensions/flask_indexd.py
  tests/conftest.py
  tests/genomic_file/test_genomic_file_resources.py
Labels: Ready for review, data model

#308 🐛 Use the db session by default in all base schemas
  dataservice/api/common/schemas.py
  tests/participant/test_participant_resources.py
  tests/test_api.py
  tests/test_ids.py
Labels: Ready for review, bug, feature

#290 ✨ Cavatica Models and Endpoints
  dataservice/__init__.py
  dataservice/api/__init__.py
  dataservice/api/biospecimen/resources.py
  dataservice/api/cavatica_app/README.md
  dataservice/api/cavatica_app/__init__.py
  dataservice/api/cavatica_app/models.py
  dataservice/api/cavatica_app/resources.py
  dataservice/api/cavatica_app/schemas.py
  dataservice/api/cavatica_task/README.md
  dataservice/api/cavatica_task/__init__.py
  dataservice/api/cavatica_task/models.py
  dataservice/api/cavatica_task/resources.py
  dataservice/api/cavatica_task/schemas.py
  dataservice/api/cavatica_task_genomic_file/README.md
  dataservice/api/cavatica_task_genomic_file/__init__.py
  dataservice/api/cavatica_task_genomic_file/resources.py
  dataservice/api/cavatica_task_genomic_file/schemas.py
  dataservice/api/genomic_file/models.py
  dataservice/api/genomic_file/resources.py
  dataservice/api/workflow/__init__.py
  dataservice/api/workflow/models.py
  docs/erd.png
  migrations/versions/64d316354133_.py
  tests/cavatica_app/test_cavatica_app_models.py
  tests/cavatica_app/test_cavatica_app_resources.py
  tests/cavatica_task/test_cavatica_task_models.py
  tests/cavatica_task/test_cavatica_task_resources.py
  tests/cavatica_task_genomic_file/test_cavatica_task_gf_resources.py
  tests/conftest.py
  tests/test_api.py
  tests/test_pagination.py
Labels: Ready for review, data model, feature

#223 📝 Update API docs to include 400, 404 responses
  dataservice/api/common/schemas.py
  dataservice/api/common/views.py
  dataservice/api/templates/delete_by_id.yml
  dataservice/api/templates/get_by_id.yml
  dataservice/api/templates/new_resource.yml
  dataservice/api/templates/update_by_id.yml
  dataservice/utils.py
Labels: Ready for review, documentation

#263 ✨ Add integration with bucket service
  config.py
  dataservice/api/study/models.py
  tests/conftest.py
  tests/genomic_file/test_genomic_file_resources.py
  tests/study/test_study_models.py
  tests/study_file/test_study_file_resources.py
  tests/test_api.py
  tests/test_pagination.py
  tests/utils.py
Labels: Ready for review, feature

#316 🔧 Bucket secret default
  config.py
  setup.py
Labels: bug, devops

#317 ✨ Basic Filter Params
  dataservice/api/README.md
  dataservice/api/biospecimen/resources.py
  dataservice/api/cavatica_app/resources.py
  dataservice/api/cavatica_task/resources.py
  dataservice/api/cavatica_task_genomic_file/resources.py
  dataservice/api/common/custom_fields.py
  dataservice/api/common/schemas.py
  dataservice/api/common/validation.py
  dataservice/api/diagnosis/resources.py
  dataservice/api/errors.py
  dataservice/api/family/resources.py
  dataservice/api/family_relationship/resources.py
  dataservice/api/genomic_file/resources.py
  dataservice/api/genomic_file/schemas.py
  dataservice/api/investigator/resources.py
  dataservice/api/outcome/resources.py
  dataservice/api/participant/resources.py
  dataservice/api/phenotype/resources.py
  dataservice/api/sequencing_center/resources.py
  dataservice/api/sequencing_center/schemas.py
  dataservice/api/sequencing_experiment/resources.py
  dataservice/api/study/resources.py
  dataservice/api/study_file/resources.py
  dataservice/api/study_file/schemas.py
  dataservice/utils.py
  requirements.txt
  tests/conftest.py
  tests/data.json
  tests/genomic_file/test_genomic_file_resources.py
  tests/study_file/test_study_file_resources.py
  tests/test_api.py
  tests/test_filter_params.py
  tests/test_pagination.py
Labels: Ready for review, feature

#331 🔧Fix reverse family relationships
  dataservice/api/family_relationship/models.py
Labels: data model, refactor

#333 🐛 Fix case sensitivity of family relationships
  dataservice/api/family_relationship/models.py
  tests/family_relationship/test_family_relationship_models.py
Labels: bug

#299 ✨ Add enum validators for entities
  dataservice/api/biospecimen/schemas.py
  dataservice/api/common/model.py
  dataservice/api/common/schemas.py
  dataservice/api/common/validation.py
  dataservice/api/diagnosis/schemas.py
  dataservice/api/genomic_file/schemas.py
  dataservice/api/outcome/schemas.py
  dataservice/api/participant/schemas.py
  dataservice/api/phenotype/schemas.py
  dataservice/api/sequencing_experiment/schemas.py
  dataservice/api/study/schemas.py
  dataservice/api/study_file/schemas.py
  tests/biospecimen/test_biospecimen_models.py
  tests/data.json
  tests/diagnosis/test_diagnosis_resources.py
  tests/genomic_file/test_genomic_file_models.py
  tests/genomic_file/test_genomic_file_resources.py
  tests/outcome/test_outcome_resources.py
  tests/participant/test_participant_models.py
  tests/participant/test_participant_resources.py
  tests/phenotype/test_phenotype_resources.py
  tests/sequencing_center/test_seq_center_models.py
  tests/sequencing_experiment/test_sequencing_experiment_resources.py
  tests/study/test_study_models.py
  tests/study/test_study_resources.py
  tests/study_file/test_study_file_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: Ready for review, feature

#279 ✨ Add SNS events for data changes
  config.py
  dataservice/api/common/views.py
  requirements.txt
  tests/test_events.py
Labels: Ready for review, feature

#324 ♻️ Refactor child links
  dataservice/api/biospecimen/schemas.py
  dataservice/api/cavatica_app/schemas.py
  dataservice/api/cavatica_task/schemas.py
  dataservice/api/family/schemas.py
  dataservice/api/family_relationship/models.py
  dataservice/api/genomic_file/schemas.py
  dataservice/api/investigator/schemas.py
  dataservice/api/participant/models.py
  dataservice/api/participant/schemas.py
  dataservice/api/sequencing_center/schemas.py
  dataservice/api/sequencing_experiment/schemas.py
  dataservice/api/study/schemas.py
  tests/family_relationship/test_family_relationship_models.py
  tests/participant/test_participant_resources.py
  tests/test_api.py
Labels: refactor

#339 🐛 Fix patch endpoint swagger spec for entities
  dataservice/api/templates/update_by_id.yml
Labels: Ready for review, bug, documentation

#341 🐛Fix paginated endpoints
  dataservice/api/biospecimen/resources.py
  dataservice/api/cavatica_app/resources.py
  dataservice/api/cavatica_task/resources.py
  dataservice/api/family/resources.py
  dataservice/api/genomic_file/resources.py
  dataservice/api/investigator/resources.py
  dataservice/api/participant/resources.py
  dataservice/api/sequencing_center/resources.py
  dataservice/api/sequencing_experiment/resources.py
  dataservice/api/study/resources.py
Labels: bug

#355 ✨Add dbgap_consent_code to biospecimen
  dataservice/api/biospecimen/models.py
  docs/erd.png
  migrations/versions/8f1ad897fb0f_.py
  tests/biospecimen/test_biospecimen_models.py
  tests/biospecimen/test_biospecimen_resources.py
  tests/data.json
Labels: Ready for review, data model

#358 🔧 Increase worker count
  bin/supervisord.conf
Labels: devops
