Repository kids-first/kf-api-dataservice, pull requests merged in 2018-08, with the labels that each got.

#394 ✨ Add biospecimen_genomic_file association table and endpoints
  dataservice/__init__.py
  dataservice/api/__init__.py
  dataservice/api/biospecimen/models.py
  dataservice/api/biospecimen/schemas.py
  dataservice/api/biospecimen_genomic_file/__init__.py
  dataservice/api/biospecimen_genomic_file/models.py
  dataservice/api/biospecimen_genomic_file/resources.py
  dataservice/api/biospecimen_genomic_file/schemas.py
  dataservice/api/cavatica_app/resources.py
  dataservice/api/cavatica_task/resources.py
  dataservice/api/cavatica_task_genomic_file/resources.py
  dataservice/api/genomic_file/models.py
  dataservice/api/genomic_file/resources.py
  dataservice/api/genomic_file/schemas.py
  dataservice/api/read_group/resources.py
  dataservice/api/sequencing_experiment/resources.py
  docs/erd.png
  migrations/versions/088f00b10226_.py
  tests/biospecimen_genomic_file/test_biospecimen_gf_resources.py
  tests/cavatica_task/test_cavatica_task_models.py
  tests/conftest.py
  tests/data.json
  tests/genomic_file/test_genomic_file_models.py
  tests/genomic_file/test_genomic_file_resources.py
  tests/read_group/test_read_group_model.py
  tests/sequencing_experiment/test_sequencingexperiment_models.py
  tests/test_api.py
  tests/test_pagination.py
Labels: data model, feature, ready-for-review

#407 ✨ Add visible to base model
  dataservice/api/common/model.py
  migrations/versions/c0f56e327e8d_.py
  tests/data.json
Labels: data model, ready-for-review, review_for_release

#408 ✨Data model changes
  dataservice/api/family/models.py
  dataservice/api/family/schemas.py
  dataservice/api/family_relationship/models.py
  dataservice/api/genomic_file/schemas.py
  dataservice/api/participant/models.py
  dataservice/api/participant/schemas.py
  docs/erd.png
  migrations/versions/9d1b39dd9af5_.py
  tests/data.json
  tests/family/test_family_models.py
  tests/family/test_family_resources.py
  tests/family_relationship/test_family_relationship_models.py
  tests/family_relationship/test_family_relationship_resources.py
  tests/participant/test_participant_models.py
  tests/participant/test_participant_resources.py
  tests/test_pagination.py
Labels: data model, ready-for-review, review_for_release

#410 🔧 Increase nginx proxy_buffer size to stop truncating repsonses
  bin/nginx.conf
Labels: devops

#401 ✨ Add biospecimen_diagnosis association table
  dataservice/__init__.py
  dataservice/api/__init__.py
  dataservice/api/biospecimen/models.py
  dataservice/api/biospecimen/resources.py
  dataservice/api/biospecimen/schemas.py
  dataservice/api/common/schemas.py
  dataservice/api/diagnosis/models.py
  dataservice/api/diagnosis/resources.py
  dataservice/api/diagnosis/schemas.py
  dataservice/api/participant/models.py
  docs/erd.png
  migrations/versions/ce01ada6ac80_.py
  tests/biospecimen/test_biospecimen_models.py
  tests/biospecimen/test_biospecimen_resources.py
  tests/conftest.py
  tests/diagnosis/test_diagnosis_models.py
  tests/diagnosis/test_diagnosis_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: data model, feature, ready-for-review, review_for_release

#413 👷 Load bucket url from vault
  config.py
Labels: devops

#416 🐛 Fix biospecimens and diagnoses links by diagnosis_id and biospecimen_id
  dataservice/api/biospecimen/resources.py
  dataservice/api/diagnosis/resources.py
  tests/biospecimen/test_biospecimen_resources.py
  tests/diagnosis/test_diagnosis_resources.py
  tests/test_api.py
  tests/test_pagination.py
Labels: bug, feature, ready-for-review

#426 ✨ Update data_type enum to support image files
  dataservice/api/genomic_file/schemas.py
Labels: feature

#430 ✨ Update analyte_type enum to support imaging files
  dataservice/api/biospecimen/schemas.py
  tests/data.json
Labels: feature, ready-for-review

#420 🐛 fix parsing of uniqueness constraint error
  dataservice/api/errors.py
  tests/test_errors.py
Labels: bug
