Repository kids-first/kf-api-dataservice, pull requests merged in 2019-05, with the labels that each got.

#514 🔊 Add response timing to logs
  bin/supervisord.conf
Labels: devops

#512 ⬆️ Bump postgres to 11.1
  .circleci/config.yml
  docker-compose.yml
Labels: devops, refactor

#516 🔊 Move log formatting to nginx.conf
  bin/nginx.conf
  bin/supervisord.conf
Labels: devops

#515 🐳 Remove venv from docker
  .dockerignore
  Dockerfile
  bin/run.sh
Labels: devops

#519 ♻️ Make Dockerfile follow best practices
  Dockerfile
Labels: refactor

#518 🐛 Individually copy files to dockerfile
  Dockerfile
Labels: bug

#522 🐛 Add missing groupby for sequencing center
  dataservice/api/sequencing_center/resources.py
  tests/test_pagination.py
Labels: bug
