Repository kids-first/kf-api-dataservice, pull requests merged in 2021-12, with the labels that each got.

#581 ✨ Add Methylation to EXPERIMENT_STRATEGY_ENUM
  dataservice/api/sequencing_experiment/schemas.py
Labels: feature

#582 📝 Update project ID in link to codacy badge
  README.md
Labels: documentation

#578 🏷 Release 1.14.0
  CHANGELOG.md
Labels: release
