Repository kids-first/kf-api-dataservice, pull requests merged in 2023-06, with the labels that each got.

#623 :busts_in_silhouette: Add codeowners
  CODEOWNERS
Labels: devops

#622 🐛 Fix indexd POST error handling
  dataservice/extensions/flask_indexd.py
  tests/genomic_file/test_genomic_file_resources.py
  tests/mocks.py
Labels: bug

#614 📝 point documentation at the kidsfirstdrc.org domain, not kids-first.io
  dataservice/api/README.md
Labels: documentation

#625 :bug: Fix port mapping in docker-compose
  README.md
  docker-compose.yml
Labels: bug
