Repository kids-first/kf-api-dataservice, pull requests merged in 2023-05, with the labels that each got.

#607 🏷 Release 1.18.0
  CHANGELOG.md
Labels: release

#610 🐛 Fix local dev setup and instructions
  README.md
  env_local.sh
Labels: documentation

#616 🐛 Fix dev setup again
  .env.sample
  README.md
  docker-compose.yml
  manage.py
Labels: bug, documentation

#611 :arrow_up: Upgrade to latest psycopg2
  requirements.txt
Labels: refactor

#619 🏷 Release 1.19.0
  CHANGELOG.md
Labels: release
