Repository kids-first/kf-api-dataservice, pull requests merged in 2024-09, with the labels that each got.

#684 👨🏻‍💻 Always bind all interfaces when app runs in docker-compose
  README.md
  docker-compose.yml
  manage.py
Labels: devops

#685 :construction_worker: Add Github Action to build and deploy dev image when merged to master
  .github/workflows/deploy.yml
Labels: devops

#686 :bug: Update GH Action to use correct branch
  .github/workflows/deploy.yml
Labels: bug, devops

#688 :bug: Update Tag of dataservice image
  .github/workflows/deploy.yml
Labels: bug

#689 🏷 Release 1.33.0
  CHANGELOG.md
Labels: release

#692 🏷 Release 1.33.1
  CHANGELOG.md
Labels: release

#694 🏷 Release 1.34.0
  CHANGELOG.md
Labels: release

#695 :bug: Force Tag info in GH action
  .github/workflows/deploy.yml
Labels: devops
